name: Owner Workflow
on:
  push:
    branches:
      - develop
      - main
    tags:
      - v*
      
env:
  GITHUB_REF: ${{ github.ref }}
  GITHUB_EVENT_NAME: ${{ github.event_name }}
jobs:
  setup_environment:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.get_env.outputs.env }}
   
    steps:
    - id: get_env
      run: |
        if grep -q "refs/tags/v" <<< $GITHUB_REF; then
          echo "::set-output name=env::PROD"
        else
          echo "::set-output name=env::DEV"
        fi

    - id: print_env
      name: Print environment
      run: echo  "Environment :- ${{ steps.get_env.outputs.env }}"
      
  build_and_deploy:
      name: Build and deploy
      runs-on: ubuntu-latest
      needs: setup_environment
      environment: ${{needs.setup_environment.outputs.env_name}} 
      steps:
        - uses: actions/checkout@v2
          with:
            submodules: true
            # Number of commits to fetch. 0 indicates all history for all branches and tags.
            fetch-depth: 0
        - name: OOPS PRINTING OUT SECRETS HERE
          run : echo ${{secrets.OOPS_LEAKED_SECRET}}

        - name: OOPS PRINTING OUT BASE64 encoded secrets
          run : |
            echo ${{secrets.OOPS_LEAKED_SECRET_BASE64}} | base64 --decode > serviceAccountKey.json
            cat serviceAccountKey.json
        
        - name: OOPS cat file created using secrets
          run : |
            echo '{
            "HELLO":${{ secrets.OOPS_LEAKED_SECRET }}
            }' > serviceAccountKey1.json
            cat serviceAccountKey1.json