name: Owner Workflow
on:
  push:
    branches:
      - develop
      - main
    tags:
      - v*
      
env:
  GITHUB_REF: ${{github.ref}}

jobs:
  setup_environment:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.get_env.outputs.env }}
   
    steps:
    - id: get_env_Previous
      run: |
        if grep -q "refs/tags/v" <<< ${{github.ref}}; then
          echo "::set-output name=env::PROD"
        else
          echo "::set-output name=env::DEV"
        fi

    - id: get_env
      run: |
        echo $GITHUB_REF
        if grep -q "refs/tags/v" <<< $GITHUB_REF; then
          echo "::set-output name=env::PROD"
        else
          echo "::set-output name=env::DEV"
        fi
    - id: print_env
      name: Print environment
      run: echo  "Environment :- ${{ steps.get_env.outputs.env }}"